[package]
name = "epics_gen_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
strum = "0.26.3"
strum_macros = "0.26.4"

[dev-dependencies]
syn = { version = "2.0", features = ["extra-traits"] }
calamine = "0.25.0"
